services:
  - type: web
    name: rag-ai-system
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        value: sqlite:///./ai_system.db
      - key: REDIS_URL
        value: redis://localhost:6379









